### ISSUE TITLE
update Python documentation via pdoc

### ISSUE THREAD

**Issue by jbathegit** [NOAA-EMC/NCEPLIBS-bufr#230]
@aerorahul @jswhit @JackReevesEyre @edwardhartnett do any of you have access to the pdoc utility or know a way to run it?  I'd like to update the Python documentation for this library, because we now have a new read_long_string() wrapper courtesy of Jack's work on #226, and it already includes the proper Markdown syntax for pdoc.  But I don't know how to run pdoc myself, because I can't find it anywhere on my local machine nor on WCOSS2, even when I have the latest Python module loaded.

For some background, our existing Python documentation is available from https://noaa-emc.github.io/NCEPLIBS-bufr/python/index.html, but that was provided to me in the past (I believe by Rahul, though I don't recall for sure), rather than being generated by anything that I know how to run myself.  Or maybe I'm just looking for pdoc in the wrong place and need a quick primer on where/how to run this myself(?)  

I'd appreciate any help or suggestions - thanks!

**Comment by JackReevesEyre** [comment]
Didi you manage to sort this @jbathegit ? I am not familiar with the pdoc package. I see that the pdoc web page (https://pdoc.dev/) only mentions pip install, but it also seems to be available on conda-forge (https://anaconda.org/conda-forge/pdoc) if that's preferable. Then running `pdoc /<rest of path>/NCEPLIBS-bufr/python/ncepbufr/` might (?) then create the new html pages equivalent to https://noaa-emc.github.io/NCEPLIBS-bufr/python/.

**Comment by jbathegit** [comment]
Thanks for the reply @JackReevesEyre.  I did some more reading, and at least on WCOSS2 I made some headway finding pdoc:

```
jeff.ator@clogin05 [~ (158)] $ module load python/3.8.6
jeff.ator@clogin05 [~ (159)] $ pip install pdoc
Defaulting to user installation because normal site-packages is not writeable
Collecting pdoc
  Downloading pdoc-12.1.0-py3-none-any.whl (127 kB)
     ââââââââââââââââââââââââââââââââââââââââ 127.2/127.2 kB 898.9 kB/s eta 0:00:00
Collecting MarkupSafe
  Downloading MarkupSafe-2.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting pygments>=2.12.0
  Downloading Pygments-2.13.0-py3-none-any.whl (1.1 MB)
     ââââââââââââââââââââââââââââââââââââââââ 1.1/1.1 MB 3.8 MB/s eta 0:00:00
Collecting Jinja2>=2.11.0
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ââââââââââââââââââââââââââââââââââââââââ 133.1/133.1 kB 19.1 MB/s eta 0:00:00
Collecting astunparse
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /apps/prod/python-modules/3.8.6/intel/19.1.3.304/lib/python3.8/site-packages (from astunparse->pdoc) (0.36.2)
Requirement already satisfied: six<2.0,>=1.6.1 in /apps/prod/python-modules/3.8.6/intel/19.1.3.304/lib/python3.8/site-packages (from astunparse->pdoc) (1.15.0)
Installing collected packages: pygments, MarkupSafe, astunparse, Jinja2, pdoc
  WARNING: The script pygmentize is installed in '/u/jeff.ator/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pdoc is installed in '/u/jeff.ator/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.1 astunparse-1.6.3 pdoc-12.1.0 pygments-2.13.0
jeff.ator@clogin05 [~ (160)] $ 
```
But then, when I tried running it to regenerate the ncepbufr pages, I got the following:

```
jeff.ator@clogin05 [~/.local/bin (166)] $ ./pdoc $HOME2/NCEPLIBS-bufr-GitHub/nceplibs-bufr/python/ncepbufr/
Warn: Error loading ncepbufr:
Traceback (most recent call last):
  File "/u/jeff.ator/.local/lib/python3.8/site-packages/pdoc/extract.py", line 211, in load_module
    return importlib.import_module(module)
  File "/apps/spack/python/3.8.6/intel/19.1.3.304/pjn2nzkjvqgmjw4hmyz43v5x4jbxjzpk/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/lfs/h2/emc/obsproc/noscrub/jeff.ator/NCEPLIBS-bufr-GitHub/nceplibs-bufr/python/ncepbufr/__init__.py", line 1, in <module>
    import _bufrlib
ModuleNotFoundError: No module named '_bufrlib'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/u/jeff.ator/.local/lib/python3.8/site-packages/pdoc/extract.py", line 254, in walk_packages2
    module = load_module(mod.name)
  File "/apps/spack/python/3.8.6/intel/19.1.3.304/pjn2nzkjvqgmjw4hmyz43v5x4jbxjzpk/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/u/jeff.ator/.local/lib/python3.8/site-packages/pdoc/extract.py", line 213, in load_module
    raise RuntimeError(f"Error importing {module}") from e
RuntimeError: Error importing ncepbufr
 (/u/jeff.ator/.local/lib/python3.8/site-packages/pdoc/extract.py:256)
pdoc server ready at http://localhost:8080


^Cjeff.ator@clogin05 [~/.local/bin (167)] $
```

So I then tried the following, to include the Python bufrlib binding, and to also redirect the output to a directory rather than have it trying to start up a webserver.  But that didn't help much either:

```
jeff.ator@clogin05 [~/.local/bin (207)] $ ./pdoc -o $TMPDIR $HOME2/NCEPLIBS-bufr-GitHub/nceplibs-bufr/python/ncepbufr /lfs/h2/emc/obsproc/noscrub/jeff.ator/NCEPLIBS-bufr-GitHub/nceplibs-bufr/python/_bufrlib.pyf
Warn: Error loading ncepbufr:
Traceback (most recent call last):
  File "/u/jeff.ator/.local/lib/python3.8/site-packages/pdoc/extract.py", line 211, in load_module
    return importlib.import_module(module)
  File "/apps/spack/python/3.8.6/intel/19.1.3.304/pjn2nzkjvqgmjw4hmyz43v5x4jbxjzpk/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/lfs/h2/emc/obsproc/noscrub/jeff.ator/NCEPLIBS-bufr-GitHub/nceplibs-bufr/python/ncepbufr/__init__.py", line 1, in <module>
    import _bufrlib
ModuleNotFoundError: No module named '_bufrlib'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/u/jeff.ator/.local/lib/python3.8/site-packages/pdoc/extract.py", line 254, in walk_packages2
    module = load_module(mod.name)
  File "/apps/spack/python/3.8.6/intel/19.1.3.304/pjn2nzkjvqgmjw4hmyz43v5x4jbxjzpk/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/u/jeff.ator/.local/lib/python3.8/site-packages/pdoc/extract.py", line 213, in load_module
    raise RuntimeError(f"Error importing {module}") from e
RuntimeError: Error importing ncepbufr
 (/u/jeff.ator/.local/lib/python3.8/site-packages/pdoc/extract.py:256)
Warn: Cannot find spec for _bufrlib (from /lfs/h2/emc/obsproc/noscrub/jeff.ator/NCEPLIBS-bufr-GitHub/nceplibs-bufr/python/_bufrlib.pyf):
Traceback (most recent call last):
  File "/u/jeff.ator/.local/lib/python3.8/site-packages/pdoc/extract.py", line 63, in walk_specs
    raise ModuleNotFoundError(modname)
ModuleNotFoundError: _bufrlib
 (/u/jeff.ator/.local/lib/python3.8/site-packages/pdoc/__init__.py:503)
Traceback (most recent call last):
  File "/u/jeff.ator/.local/lib/python3.8/site-packages/pdoc/extract.py", line 211, in load_module
    return importlib.import_module(module)
  File "/apps/spack/python/3.8.6/intel/19.1.3.304/pjn2nzkjvqgmjw4hmyz43v5x4jbxjzpk/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/lfs/h2/emc/obsproc/noscrub/jeff.ator/NCEPLIBS-bufr-GitHub/nceplibs-bufr/python/ncepbufr/__init__.py", line 1, in <module>
    import _bufrlib
ModuleNotFoundError: No module named '_bufrlib'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./pdoc", line 8, in <module>
    sys.exit(cli())
  File "/u/jeff.ator/.local/lib/python3.8/site-packages/pdoc/__main__.py", line 192, in cli
    pdoc.pdoc(
  File "/u/jeff.ator/.local/lib/python3.8/site-packages/pdoc/__init__.py", line 504, in pdoc
    all_modules[module_name] = doc.Module.from_name(module_name)
  File "/u/jeff.ator/.local/lib/python3.8/site-packages/pdoc/doc.py", line 381, in from_name
    return cls(extract.load_module(name))
  File "/apps/spack/python/3.8.6/intel/19.1.3.304/pjn2nzkjvqgmjw4hmyz43v5x4jbxjzpk/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/u/jeff.ator/.local/lib/python3.8/site-packages/pdoc/extract.py", line 213, in load_module
    raise RuntimeError(f"Error importing {module}") from e
RuntimeError: Error importing ncepbufr
jeff.ator@clogin05 [~/.local/bin (208)] $
```
It definitely seems like I'm missing something here.  I'm not sure why it would need access to the actual bufrlib library, because that's all written in C and Fortran and uses doxygen (rather than pdoc) to generate its documentation.  In short, I would think that access to the _bufrlib.pyf binding should be enough, unless I'm still not calling pdoc correctly(?)

If anyone else (@jswhit, @aerorahul, @edwardhartnett, others?) can spot anything wrong I'm doing here or knows how to correctly run pdoc, please let me know - thanks!
